#!/bin/bash
source /code/shell_scripts/train_n_serve.sh
echo "Training initial models..."
train_n_serve "asset.variety" "Server" "LGBM" 5010 "--training" "--serving"
train_n_serve "asset.variety" "User Dev" "LGBM" 5011 "--training" "--serving"
train_n_serve "asset.variety" "Network" "LGBM" 5012 "--training" "--serving"
train_n_serve "asset.assets.variety.S" "Database" "LGBM" 5013 "--training" "--serving"
train_n_serve "asset.assets.variety.S" "Web application" "LGBM" 5014 "--training" "--serving"
train_n_serve "asset.assets.variety.U" "Desktop or laptop" "LGBM" 5015 "--training" "--serving"
train_n_serve "action" "Malware" "LGBM" 5020 "--training" "--serving"
train_n_serve "action" "Hacking" "LGBM" 5021 "--training" "--serving"
train_n_serve "action.malware.variety" "Ransomware" "LGBM" 5022 "--training" "--serving"
train_n_serve "action.hacking.variety" "DoS" "LGBM" 5023 "--training" "--serving"
train_n_serve "action.hacking.variety" "SQLi" "LGBM" 5024 "--training" "--serving"
train_n_serve "action.hacking.variety" "Brute force" "LGBM" 5025 "--training" "--serving"
train_n_serve "action.hacking.variety" "Use of backdoor or C2" "LGBM" 5026 "--training" "--serving"
train_n_serve "attribute" "Confidentiality" "LGBM" 5030 "--training" "--serving"
train_n_serve "attribute" "Integrity" "LGBM" 5031 "--training" "--serving"
train_n_serve "attribute" "Availability" "LGBM" 5032 "--training" "--serving"
tail -F "KeepingContainerAlive"