#!/bin/bash
source /code/shell_scripts/train_n_serve.sh
echo "Training initial models..."
train_n_serve "asset.variety" "Server" "LGBM RF KNN" 5010 "--training" "--serving"
train_n_serve "asset.variety" "User Dev" "LGBM RF KNN" 5011 "--training" "--serving"
train_n_serve "asset.variety" "Network" "LGBM RF KNN" 5012 "--training" "--serving"
train_n_serve "asset.assets.variety.S" "Database" "LGBM RF KNN" 5013 "--training" "--serving"
train_n_serve "asset.assets.variety.S" "Web application" "LGBM RF KNN" 5014 "--training" "--serving"
train_n_serve "asset.assets.variety.U" "Desktop or laptop" "LGBM RF KNN" 5015 "--training" "--serving"
train_n_serve "action" "Malware" "LGBM RF KNN" 5020 "--training" "--serving"
train_n_serve "action" "Hacking" "LGBM RF KNN" 5021 "--training" "--serving"
train_n_serve "action.malware.variety" "Ransomware" "LGBM RF KNN" 5022 "--training" "--serving"
train_n_serve "action.hacking.variety" "DoS" "LGBM RF KNN" 5023 "--training" "--serving"
train_n_serve "action.hacking.variety" "SQLi" "LGBM RF KNN" 5024 "--training" "--serving"
train_n_serve "action.hacking.variety" "Brute force" "LGBM RF KNN" 5025 "--training" "--serving"
train_n_serve "action.hacking.variety" "Use of backdoor or C2" "LGBM RF KNN" 5026 "--training" "--serving"
train_n_serve "attribute" "Confidentiality" "LGBM RF KNN" 5030 "--training" "--serving"
train_n_serve "attribute" "Integrity" "LGBM RF KNN" 5031 "--training" "--serving"
train_n_serve "attribute" "Availability" "LGBM RF KNN" 5032 "--training" "--serving"
tail -F "KeepingContainerAlive"